/**
 * Medi.AI - Backend Connected Version
 */

// 🔹 Change this only if your backend URL changes
 const BASE_URL = "https://health-backend-1-3iyq.onrender.com";


// ===============================
// 1️⃣ Navigation Controller
// ===============================
function navTo(view) {
    document.querySelectorAll('.page-view').forEach(v => v.classList.add('hidden'));
    const target = document.getElementById(`view-${view}`);
    if (target) {
        target.classList.remove('hidden');
        target.classList.add('animate-in');
    }

    if (view === 'doctor') populateQueue();
}


// ===============================
// 2️⃣ Patient Step Controller
// ===============================
function moveStep(step) {
    document.querySelectorAll('.space-block').forEach(s => s.classList.add('hidden'));
    document.querySelectorAll('.step-dot').forEach(d => d.classList.remove('active'));

    const space = document.getElementById(`patient-space-${step}`);
    if (space) {
        space.classList.remove('hidden');
        space.classList.add('animate-in');
    }

    for (let i = 1; i <= step; i++) {
        const dot = document.getElementById(`step-dot-${i}`);
        if (dot) dot.classList.add('active');
    }
}


// ===============================
// 3️⃣ Connect To Backend (REAL AI)
// ===============================
function triggerAI() {
    const btn = event.target;
    btn.innerHTML = '<i class="fas fa-circle-notch animate-spin mr-2"></i> Connecting to AI Server...';
    btn.disabled = true;

    const symptoms = document.getElementById('p_symptoms').value;

    if (!symptoms) {
        alert("Please enter symptoms.");
        btn.disabled = false;
        btn.innerHTML = "Start AI Risk Stratification";
        return;
    }

    fetch(`${BASE_URL}/predict`, {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            symptom: symptoms
        })
    })
    .then(response => response.json())
    .then(data => {

        // Update Risk
        document.getElementById('risk-text').innerText = data.risk;

        if (data.risk === "HIGH") {
            document.getElementById('risk-text').className = "text-red-500";
        } else {
            document.getElementById('risk-text').className = "text-emerald-500";
        }

        // Update Department
        document.getElementById('rec-dept').innerText = data.department;

        // Insight text
        document.getElementById('ai_insight').innerText =
            "Result generated by deployed FastAPI ML backend.";

        moveStep(3);
        renderFactorChart();

        btn.innerHTML = "Start AI Risk Stratification";
        btn.disabled = false;
    })
    .catch(error => {
        console.error("Backend Error:", error);
        alert("Backend connection failed. Try again.");
        btn.innerHTML = "Start AI Risk Stratification";
        btn.disabled = false;
    });
}


// ===============================
// 4️⃣ Chart.js Visualization
// ===============================
function renderFactorChart() {
    const canvas = document.getElementById('factorChart');
    if (!canvas) return;

    const ctx = canvas.getContext('2d');

    new Chart(ctx, {
        type: 'radar',
        data: {
            labels: ['Vitals', 'Symptom Match', 'History', 'Age', 'Rule Override'],
            datasets: [{
                data: [80, 90, 50, 40, 70],
                backgroundColor: 'rgba(16,185,129,0.2)',
                borderColor: '#10B981',
                borderWidth: 2
            }]
        },
        options: {
            plugins: { legend: { display: false } },
            scales: { r: { ticks: { display: false } } }
        }
    });
}


// ===============================
// 5️⃣ Doctor Dashboard Mock Queue
// ===============================
const mockPatients = [
    { name: "Alice Smith", age: 67, symptoms: "Dyspnea", score: 98 },
    { name: "Robert Fox", age: 42, symptoms: "Fatigue", score: 22 }
];

function populateQueue() {
    const table = document.getElementById('doctor-queue');
    if (!table) return;

    table.innerHTML = "";

    mockPatients.forEach(p => {
        table.innerHTML += `
            <tr class="hover:bg-slate-50">
                <td class="p-6 font-bold">${p.name}</td>
                <td class="p-6">${p.symptoms}</td>
                <td class="p-6 text-center font-black">${p.score}%</td>
                <td class="p-6">General</td>
                <td class="p-6">
                    <button class="bg-emerald-500 text-white px-3 py-1 rounded">Review</button>
                </td>
            </tr>
        `;
    });
}


// ===============================
// 6️⃣ Warm Up Backend On Page Load
// ===============================
window.addEventListener("load", () => {
    fetch(BASE_URL)
        .then(() => console.log("Backend warmed up"))
        .catch(() => console.log("Backend sleeping"));
});
